# Télécharger une image Java
FROM eclipse-temurin:21-jre

# Créer le répertoire de travail
WORKDIR /app

# Copier le fichier JAR
COPY sip_academy-0.0.1-SNAPSHOT.jar /app/sip_academy-0.0.1-SNAPSHOT.jar

# Exposer le port Spring Boot
EXPOSE 8087

# Démarrer l'application
CMD ["java", "-jar", "sip_academy-0.0.1-SNAPSHOT.jar"]